# -*- coding: utf-8 -*-
"""Regenerate ROSTER.md (gitignored — contains student PII).

The roster used to live in the root README; it moved out so the README can be
published. The table between the saais markers is regenerated on every write."""
import os
import re
import urllib.parse
from datetime import date

from ..repo import paths

BEGIN = "<!-- saais:begin roster -->"
END = "<!-- saais:end roster -->"

HEADER = """# Advisee roster

*This file is generated by SAAIS and is gitignored (it contains student PII).
Do not hand-edit between the markers — edits there are overwritten.*

"""

LEGEND = ("\nStatus legend: 🟢 on track (no flags) · 🟡 watch (INCs / a retake pending) · "
          "🔴 needs attention (recent delinquency, ≥3 retakes, or no current enrollment).\n")


def _link(st):
    rel = os.path.relpath(st.folder_path, paths.ROOT).replace(os.sep, "/")
    return "(" + urllib.parse.quote(rel) + "/)"


def render_table(students):
    L = [f"## Active advisees ({len(students)}) — as of {date.today().isoformat()}", ""]
    L.append("| Student | ID | Curriculum | Year level | Units | GWA | Status | Flags |")
    L.append("|---|---|---|---|---|---|---|---|")
    order = {"🔴": 0, "🟡": 1, "🟢": 2, "⚪": 3}
    for st in sorted(students, key=lambda s: (order.get(s.status[:1], 9), s.name)):
        name = st.name.title()
        if st.an:
            an = st.an
            gwa = f"{an['gwa']:.2f}" if an["gwa"] else "—"
            L.append(f"| [{name}]{_link(st)} | {st.sid} | {an['curkey']} | {an['year_level']} |"
                     f" {an['units']:g} | {gwa} | {st.status} | {len(an['flags'])} |")
        else:
            L.append(f"| [{name}]{_link(st)} | {st.sid or '—'} | — | — | — | — |"
                     f" {st.status} | — |")
    return "\n".join(L) + LEGEND


def sync(students):
    table = BEGIN + "\n" + render_table(students) + END
    if os.path.exists(paths.ROSTER_MD):
        with open(paths.ROSTER_MD, encoding="utf-8") as fh:
            text = fh.read()
        if BEGIN in text and END in text:
            text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda m: table, text, flags=re.S)
        else:
            text = text.rstrip("\n") + "\n\n" + table + "\n"
    else:
        text = HEADER + table + "\n"
    with open(paths.ROSTER_MD, "w", encoding="utf-8") as fh:
        fh.write(text)
    return paths.ROSTER_MD
